BlogProje/BlogProje/Controllers/AboutController.cs
using BusinessLayer.Conrete;
using DataAccessLayer.EntityFramework;
using EntityLayer.Conrete;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BlogProje.Controllers
{
    [AllowAnonymous]
    public class AboutController : Controller
    {
        // GET: About
        AboutManager abm = new AboutManager(new EfAboutDal());
        public ActionResult Index()
        {
            var aboutcontent = abm.GetList();
            return View(aboutcontent);
        }
        public PartialViewResult Footer()
        {            
            var aboutcontentlist= abm.GetList();
            return PartialView(aboutcontentlist);
        }
        public PartialViewResult MeetTheTeam()
        {
            AuthorManager autman = new AuthorManager(new EfAuthorDal());
            var authorlist = autman.GetList();
            return PartialView(authorlist);
        }

        [HttpGet]
        public ActionResult UpdateAboutList()
        {
            var aboutlist = abm.GetList();
            return View(aboutlist);
        }

        [HttpPost]
        public ActionResult UpdateAbout(About p)
        {
            abm.AboutUpdate(p);
            return RedirectToAction("UpdateAboutList");
        }
    }
}

BlogProje/BlogProje/Controllers/BlogController.cs
using BusinessLayer.Conrete;
using BusinessLayer.ValidationRules;
using DataAccessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using EntityLayer.Conrete;
using FluentValidation.Results;
using PagedList;
using PagedList.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BlogProje.Controllers
{
    public class BlogController : Controller
    {
        // GET: Blog
        BlogManager bm = new BlogManager(new EfBlogDal());
        CommentManager cm = new CommentManager(new EfCommentDal());
        AuthorManager authormanager = new AuthorManager(new EfAuthorDal());


        [AllowAnonymous]
        public ActionResult Index()
        {
            return View();
        }

        [AllowAnonymous]
        public PartialViewResult BlogList(int page=1)
        {
            var bloglist = bm.GetList().ToPagedList(page,6);
            return PartialView(bloglist);
        }

        [AllowAnonymous]
        public PartialViewResult FeaturedPosts()
        {
            //1.Post
            var posttitle1 = bm.GetList().OrderByDescending(x=>x.BlogID).Where(a => a.CategoryID == 1).Select(b => b.BlogTitle).FirstOrDefault();
            var postimage1= bm.GetList().OrderByDescending(x => x.BlogID).Where(a => a.CategoryID == 1).Select(b => b.BlogImage).FirstOrDefault();
            var blogdate1= bm.GetList().OrderByDescending(x => x.BlogID).Where(a => a.CategoryID == 1).Select(b => b.BlogDate).FirstOrDefault();
            var blogpostid1 = bm.GetList().OrderByDescending(x => x.BlogID).Where(a => a.CategoryID == 1).Select(b => b.BlogID).FirstOrDefault();

            ViewBag.posttitle1 = posttitle1;
            ViewBag.postimage1 = postimage1;
            ViewBag.blogdate1 = blogdate1;
            ViewBag.blogpostid1 = blogpostid1;

            //2.Post
            var posttitle2 = bm.GetList().OrderByDescending(x => x.BlogID).Where(a => a.CategoryID == 2).Select(b => b.BlogTitle).FirstOrDefault();
            var postimage2 = bm.GetList().OrderByDescending(x => x.BlogID).Where(a => a.CategoryID == 2).Select(b => b.BlogImage).FirstOrDefault();
            var blogdate2 = bm.GetList().OrderByDescending(x => x.BlogID).Where(a => a.CategoryID == 2).Select(b => b.BlogDate).FirstOrDefault();
            var blogpostid2 = bm.GetList().OrderByDescending(x => x.BlogID).Where(a => a.CategoryID == 2).Select(b => b.BlogID).FirstOrDefault();

            ViewBag.posttitle2 = posttitle2;
            ViewBag.postimage2 = postimage2;
            ViewBag.blogdate2 = blogdate2;
            ViewBag.blogpostid2 = blogpostid2;


            //3.Post
            var posttitle3 = bm.GetList().OrderByDescending(x => x.BlogID).Where(a => a.CategoryID == 6).Select(b => b.BlogTitle).FirstOrDefault();
            var postimage3 = bm.GetList().OrderByDescending(x => x.BlogID).Where(a => a.CategoryID == 6).Select(b => b.BlogImage).FirstOrDefault();
            var blogdate3 = bm.GetList().OrderByDescending(x => x.BlogID).Where(a => a.CategoryID == 6).Select(b => b.BlogDate).FirstOrDefault();
            var blogpostid3 = bm.GetList().OrderByDescending(x => x.BlogID).Where(a => a.CategoryID == 6).Select(b => b.BlogID).FirstOrDefault();


            ViewBag.posttitle3 = posttitle3;
            ViewBag.postimage3 = postimage3;
            ViewBag.blogdate3 = blogdate3;
            ViewBag.blogpostid3 = blogpostid3;


            //4.Post
            var posttitle4 = bm.GetList().OrderByDescending(x => x.BlogID).Where(a => a.CategoryID == 4).Select(b => b.BlogTitle).FirstOrDefault();
            var postimage4 = bm.GetList().OrderByDescending(x => x.BlogID).Where(a => a.CategoryID == 4).Select(b => b.BlogImage).FirstOrDefault();
            var blogdate4 = bm.GetList().OrderByDescending(x => x.BlogID).Where(a => a.CategoryID == 4).Select(b => b.BlogDate).FirstOrDefault();
            var blogpostid4 = bm.GetList().OrderByDescending(x => x.BlogID).Where(a => a.CategoryID == 4).Select(b => b.BlogID).FirstOrDefault();


            ViewBag.posttitle4 = posttitle4;
            ViewBag.postimage4 = postimage4;
            ViewBag.blogdate4 = blogdate4;
            ViewBag.blogpostid4 = blogpostid4;


            //5.Post
            var posttitle5 = bm.GetList().OrderByDescending(x => x.BlogID).Where(a => a.CategoryID == 5).Select(b => b.BlogTitle).FirstOrDefault();
            var postimage5 = bm.GetList().OrderByDescending(x => x.BlogID).Where(a => a.CategoryID == 5).Select(b => b.BlogImage).FirstOrDefault();
            var blogdate5 = bm.GetList().OrderByDescending(x => x.BlogID).Where(a => a.CategoryID == 5).Select(b => b.BlogDate).FirstOrDefault();
            var blogpostid5 = bm.GetList().OrderByDescending(x => x.BlogID).Where(a => a.CategoryID == 5).Select(b => b.BlogID).FirstOrDefault();


            ViewBag.posttitle5 = posttitle5;
            ViewBag.postimage5 = postimage5;
            ViewBag.blogdate5 = blogdate5;
            ViewBag.blogpostid5 = blogpostid5;


            return PartialView();
        }
       
        [AllowAnonymous]
        public PartialViewResult OtherPosts()
        {
            return PartialView();
        }

        [AllowAnonymous]
        public ActionResult BlogDetails()
        {
            return View();
        }

        [AllowAnonymous]
        public PartialViewResult BlogCover(int id)
        {
            var BlogDetailsList = bm.GetBlogByID(id);
            return PartialView(BlogDetailsList);
        }

        [AllowAnonymous]
        public PartialViewResult BlogReadAll(int id)
        {
            var BlogDetailsList = bm.GetBlogByID(id);
            return PartialView(BlogDetailsList);
        }

        [AllowAnonymous]
        public ActionResult BlogByCategory(int id)
        {
            var BlogListByCategory = bm.GetBlogByCategory(id);
            var CategoryName = bm.GetBlogByCategory(id).Select(a => a.Category.CategoryName).FirstOrDefault();
            ViewBag.CategoryName = CategoryName;
            var CategoryDescreption = bm.GetBlogByCategory(id).Select(a => a.Category.CategoryDescreption).FirstOrDefault();
            ViewBag.CategoryDescreption = CategoryDescreption;
            return View(BlogListByCategory);
        }
        public ActionResult AdminBlogList()
        {
            var bloglist = bm.GetList();
            return View(bloglist);
        }
        public ActionResult AdminBlogList2()
        {
            var bloglist = bm.GetList();
            return View(bloglist);
        }

        public ActionResult AdminBlogDetails(int id)
        {
            var adminBlogDetails = bm.GetBlogByID(id);
            return View(adminBlogDetails);
        }

        public ActionResult AuthorBlogDetails(int id)
        {
            var authorBlogDetails = bm.GetBlogByID(id);
            return View(authorBlogDetails);
        }

        public ActionResult AuthorBlogList2()
        {
            var bloglist = bm.GetList();
            return View(bloglist);
        }



        [HttpGet]
        public ActionResult AddNewBlog()
        {
            Context c = new Context();
            List<SelectListItem> values = (from a in c.Categories.ToList()
                                           select new SelectListItem
                                           {
                                               Text = a.CategoryName,
                                               Value = a.CategoryID.ToString()
                                           }).ToList();
            ViewBag.values = values;

            List<SelectListItem> values2 = (from a in c.Authors.ToList()
                                           select new SelectListItem
                                           {
                                               Text = a.AuthorName,
                                               Value = a.AuthorID.ToString()
                                           }).ToList();
            ViewBag.values2 = values2;

            return View();
        }

        [HttpPost]
        public ActionResult AddNewBlog(Blog p)
        {
            p.BlogDate = DateTime.Parse(DateTime.Now.ToShortDateString());
            bm.TAdd(p);
            return RedirectToAction("AdminBlogList");
        }

        public ActionResult DeleteBlog(int id)
        {
            Blog blog = bm.GetByID(id);
            bm.TDelete(blog);
            return RedirectToAction("AdminBlogList");
        }

        public ActionResult AuthorDeleteBlog(int id)
        {
            Blog blog = bm.GetByID(id);
            bm.TDelete(blog);
            return RedirectToAction("BlogList", "User");
        }

        [HttpGet]
        public ActionResult UpdateBlog(int id)
        {

            Blog blog = bm.GetByID(id);
            Context c = new Context();
            List<SelectListItem> values = (from a in c.Categories.ToList()
                                           select new SelectListItem
                                           {
                                               Text = a.CategoryName,
                                               Value = a.CategoryID.ToString()
                                           }).ToList();
            ViewBag.values = values;

            List<SelectListItem> values2 = (from a in c.Authors.ToList()
                                            select new SelectListItem
                                            {
                                                Text = a.AuthorName,
                                                Value = a.AuthorID.ToString()
                                            }).ToList();
            ViewBag.values2 = values2;
            return View(blog);
        }

        [HttpPost]
        public ActionResult UpdateBlog(Blog p)
        {
            bm.TUpdate(p);
            return RedirectToAction("AdminBlogList");
        }

        public ActionResult GetCommentByBlog(int id)
        {

BlogProje/BlogProje/Controllers/MailSubscribeController.cs
using BusinessLayer.Conrete;
using DataAccessLayer.EntityFramework;
using EntityLayer.Conrete;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BlogProje.Controllers
{
    [AllowAnonymous]
    public class MailSubscribeController : Controller
    {
        SubscribeMailManager sm = new SubscribeMailManager(new EfSubscribeMailDal());

        [HttpGet] 
        public PartialViewResult AddMail()
        {
            return PartialView();
        }

        [HttpPost]
        public PartialViewResult AddMail(SubscribeMail p)
        {            
            sm.TAdd(p);
            return PartialView();
        }

    }
}

BlogProje/BlogProje/Views/Blog/AddNewBlog.cshtml
@model EntityLayer.Conrete.Blog
@{
    ViewBag.Title = "AddNewBlog";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<form class="form-group" method="post">
    @Html.Label("Blog Başlığı")
    @Html.TextBoxFor(a => a.BlogTitle, new { @class = "form-control" })
    @Html.ValidationMessageFor(a => a.BlogTitle)
    <br />
    @Html.Label("Blog Kategori")
    @Html.DropDownListFor(a => a.CategoryID, (List<SelectListItem>)ViewBag.values, new { @class = "form-control" })
    @Html.ValidationMessageFor(a => a.CategoryID)
    <br />
    @Html.Label("Blog Resimi")
    @Html.TextBoxFor(a => a.BlogImage, new { @class = "form-control" })
    @Html.ValidationMessageFor(a => a.BlogImage)
    <br />
    @Html.Label("Blog Tarihi")
    @Html.TextBoxFor(a => a.BlogDate, new { @class = "form-control" })
    @Html.ValidationMessageFor(a => a.BlogDate)
    <br />
    @Html.Label("Blog Yazarı")
    @Html.DropDownListFor(a => a.AuthorID, (List<SelectListItem>)ViewBag.values2, new { @class = "form-control" })
    @Html.ValidationMessageFor(a => a.AuthorID)
    <br />
    @Html.Label("Blog İçeriği")
    @Html.TextAreaFor(a => a.BlogContent, 10, 20, new { @class = "form-control" })
    @Html.ValidationMessageFor(a => a.BlogContent)
    <br />
    <button class="btn btn-info">Yükle</button>
</form>

BlogProje/BlogProje/Views/Blog/AdminBlogDetails.cshtml
@model IEnumerable<EntityLayer.Conrete.Blog>
@{
    ViewBag.Title = "AdminBlogDetails";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<link href="https://fonts.googleapis.com/css?family=Muli:300,400,700|Playfair+Display:400,700,900" rel="stylesheet">
<link rel="stylesheet" href="~/miniblog/miniblog/css/style.css">

@foreach (var item in Model)
{

    <div  class="site-cover site-cover-sm same-height overlay single-page" style="background-image: url('@item.BlogImage'); width:auto; height:595px;">
        <div class="container">
            <div class="row same-height justify-content-center">
                <div class="col-md-12 col-lg-10">
                    <div class="post-entry" style="text-align:center">
                        <span class="post-category text-white bg-success mb-3">@item.Category.CategoryName</span>
                        <h1 class="mb-4"><a href="#">@item.BlogTitle</a></h1>
                        <div class="post-meta align-items-center text-center">
                            <figure class="author-figure mb-0 mr-3 d-inline-block"><img src="@item.Author.AuthorImage" alt="Image" class="img-fluid"></figure>
                            <span class="d-inline-block mt-1">@item.Author.AuthorName</span>
                            <span>&nbsp;-&nbsp; @(((DateTime)item.BlogDate).ToString("dd-MMM-yyyy"))</span>
                            <br />
                            <span class="d-inline-block mt-1">12dk Okuma süresi</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>


                    <br />
                    <section class="site-section py-lg">
                        <div class="container">
                            <div class="row blog-entries element-animate">

                                <div class="col-md-12 col-lg-8 main-content">
                                    <div class="post-content-body">
                                        <p>@item.BlogContent .</p>
                                        <div class="row mb-5 mt-5">
                                            <div class="col-md-12 mb-4">
                                                
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </section>
                }

BlogProje/BlogProje/Views/Blog/AdminBlogList2.cshtml
@model IEnumerable<EntityLayer.Conrete.Blog>
@{
    ViewBag.Title = "AdminBlogList2";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
@{string color = ""; }
@{string casename = ""; }
@{int puan = 1; }
<!DOCTYPE html>
<html>
<body class="hold-transition sidebar-mini">
    <!-- Main content -->
    <section class="content">
        <!-- Default box -->
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">Bloglar</h3>
                <div class="card-tools">

                    <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip" title="Collapse">
                        <i class="fas fa-minus"></i>
                    </button>

                    <button type="button" class="btn btn-tool" data-card-widget="remove" data-toggle="tooltip" title="Remove">
                        <i class="fas fa-times"></i>
                    </button>
                </div>
            </div>

            <div class="card-body p-0">
                <table class="table table-striped projects">
                    <thead>
                        <tr>
                            <th style="width: 1%">
                                ID
                            </th>

                            <th style="width: 20%">
                                Blog Adı
                            </th>

                            <th style="width: 20%">
                                Yazar
                            </th>

                            <th style="width: 15%">
                                Beğeni Oranı
                            </th>

                            <th style="width: 8%" class="text-center">
                                Kategori
                            </th>

                            <th style="width: 20%">
                            </th>
                        </tr>
                    </thead>

                    <tbody>

                        @foreach (var item in Model)
                        {
                            puan = item.BlogRating * 10;

                            if (puan >= 90)
                            {
                                color = "post-category text-white bg-success mb-3";
                                casename = "Çok İyi";
                            }
                            if (puan >= 70 && puan <= 89)
                            {
                                color = "post-category text-white bg-info mb-3";
                                casename = "İyi";
                            }
                            if (puan >= 50 && puan <= 69)
                            {
                                color = "post-category text-white bg-warning mb-3";
                                casename = "Fena değil";
                            }
                            if (puan >= 0 && puan <= 49)
                            {
                                color = "post-category text-white bg-danger mb-3";
                                casename = "Kötü";
                            }
                        }


                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    @item.BlogID
                                </td>

                                <td>
                                    @item.BlogTitle
                                </td>

                                <td>
                                    <ul class="list-inline">
                                        <li class="list-inline-item">
                                            <img alt="Avatar" class="table-avatar" src="@item.Author.AuthorImage"> &nbsp &nbsp
                                            @item.Author.AuthorName
                                        </li>

                                    </ul>
                                </td>

                                <td class="project_progress">
                                    <div class="progress progress-sm">
                                        <div class="progress-bar bg-green" role="progressbar" aria-volumenow="57" aria-volumemin="0" aria-volumemax="100" style="width: @puan%">
                                        </div>
                                    </div>

                                    <small>
                                        @puan Reyting
                                    </small>
                                </td>

                                <td class="project-state">
                                    <span class="badge badge-secondary">@item.Category.CategoryName</span>
                                </td>

                                <td class="project-actions text-right">
                                    <a class="btn btn-primary btn-sm" href="/Blog/AdminBlogDetails/@item.BlogID">
                                        <i class="fas fa-folder"></i>
                                        Sitede Gör
                                    </a>
                                    <a class="btn btn-danger btn-sm" href="Blog/DeleteBlog/@item.BlogID">
                                        <i class="fas fa-trash"></i>
                                        Sil
                                    </a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
            <!-- /.card-body -->
        </div>
        <!-- /.card -->
    </section>
</body>
</html>

BlogProje/BlogProje/Views/Blog/AuthorBlogDetails.cshtml
@model IEnumerable<EntityLayer.Conrete.Blog>
@{
    ViewBag.Title = "AuthorBlogDetails";
    Layout = "~/Views/Shared/_AuthorLayout.cshtml";
}


<link href="https://fonts.googleapis.com/css?family=Muli:300,400,700|Playfair+Display:400,700,900" rel="stylesheet">
<link rel="stylesheet" href="~/miniblog/miniblog/css/style.css">

@{int dk = 1; }
@{string casename = ""; }

@foreach (var item in Model)
{
    dk = item.BlogContent.Length;

    if (dk >= 1500)
    {
        casename = "15 dk";
    }
    if (dk >= 1000 && dk <= 1499)
    {
        casename = " 12 dk";
    }
    if (dk >= 500 && dk <= 999)
    {
        casename = "10 dk";
    }
    if (dk >= 1 && dk <= 499)
    {
        casename = "5 dk";
    }
}

@foreach (var item in Model)
{

    <div class="site-cover site-cover-sm same-height overlay single-page" style="background-image: url('@item.BlogImage'); width:auto; height:720px;">
        <div class="container">
            <div class="row same-height justify-content-center">
                <div class="col-md-12 col-lg-10">
                    <div class="post-entry" style="text-align:center">
                        <span class="post-category text-white bg-success mb-3">@item.Category.CategoryName</span>
                        <h1 class="mb-4"><a href="#">@item.BlogTitle</a></h1>
                        <div class="post-meta align-items-center text-center">
                            <figure class="author-figure mb-0 mr-3 d-inline-block"><img src="@item.Author.AuthorImage" alt="Image" class="img-fluid"></figure>
                            <span class="d-inline-block mt-1">@item.Author.AuthorName</span>
                            <span>&nbsp;-&nbsp; @(((DateTime)item.BlogDate).ToString("dd-MMM-yyyy"))</span>
                            <br />
                            <span class="d-inline-block mt-1">Tahmini Okuma süresi @casename</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>


    <br />
    <section class="site-section py-lg">
        <div class="container">
            <div class="row blog-entries element-animate">

                <div class="col-md-12 col-lg-8 main-content">
                    <div class="post-content-body">
                        <p>@item.BlogContent .</p>
                        <div class="row mb-5 mt-5">
                            <div class="col-md-12 mb-4">

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
}

BlogProje/BlogProje/Views/Blog/AuthorBlogList.cshtml
@{
    ViewBag.Title = "AuthorBlogList";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

@{string color = ""; }
@{string casename = ""; }
<!DOCTYPE html>
<html>
<body class="hold-transition sidebar-mini">
    <!-- Main content -->
    <section class="content">
        <!-- Default box -->
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">Bloglarım</h3>
                <div class="card-tools">

                    <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip" title="Collapse">
                        <i class="fas fa-minus"></i>
                    </button>

                    <button type="button" class="btn btn-tool" data-card-widget="remove" data-toggle="tooltip" title="Remove">
                        <i class="fas fa-times"></i>
                    </button>
                </div>
            </div>

            <div class="card-body p-0">
                <table class="table table-striped projects">
                    <thead>
                        <tr>
                            <th style="width: 1%">
                                ID
                            </th>

                            <th style="width: 20%">
                                Blog Başlığı
                            </th>

                            <th style="width: 30%">
                                Blog Değerlendirme Oranı
                            </th>

                            <th style="width: 8%" class="text-center">
                                Durum
                            </th>

                            <th style="width: 20%">
                            </th>
                        </tr>
                    </thead>

                    <tbody>
                        @foreach (var item in Model)
                        {

                            if (item.BlogRating >= 85)
                            {
                                color = "post-category text-white bg-success mb-3";
                                casename = "Çok İyi";
                            }
                            if (item.BlogRating >= 70 && item.BlogRating <= 84)
                            {
                                color = "post-category text-white bg-info mb-3";
                                casename = "İyi";
                            }
                            if (item.BlogRating >= 50 && item.BlogRating <= 69)
                            {
                                color = "post-category text-white bg-warning mb-3";
                                casename = "Fena değil";
                            }
                            if (item.BlogRating >= 0 && item.BlogRating <= 49)
                            {
                                color = "post-category text-white bg-danger mb-3";
                                casename = "Kötü";
                            }


                            <tr>
                                <td>
                                    @item.BlogID
                                </td>

                                <td>
                                    @item.BlogTitle
                                </td>

                                <td class="project_progress">
                                    <div class="progress progress-sm">
                                        <div class="progress-bar bg-green" role="progressbar" aria-volumenow="10" aria-volumemin="0" aria-volumemax="10" style="width: @item.BlogRating% ">
                                        </div>
                                    </div>

                                    <small>
                                        Aldığı Puan @item.BlogRating
                                    </small>
                                </td>

                                <td class="project-state">
                                    <span class="badge badge-@color">@casename</span>
                                </td>

                                <td class="project-actions text-right">

                                    
                                    <a class="btn btn-danger btn-sm" href="#">
                                        <i class="fas fa-trash"></i>
                                        Sil
                                    </a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
            <!-- /.card-body -->
        </div>
        <!-- /.card -->
    </section>
</body>
</html>

BlogProje/BlogProje/Views/Blog/BlogByCategory.cshtml
@model IEnumerable<EntityLayer.Conrete.Blog>
@{
    ViewBag.Title = "BlogByCategory";
    Layout = "~/Views/Shared/Layoutt.cshtml";
}

<div class="py-5 bg-light">
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <span>Kategori</span>
                <h3>@ViewBag.CategoryName</h3>
                <p>@ViewBag.CategoryDescreption</p>

            </div>
        </div>
    </div>
</div>
<div class="site-section bg-white">
    <div class="container">
        <div class="row">
            @foreach (var item in Model)
             {
                <div class="col-lg-4 mb-4">
                    <div class="entry2">
                        <a href="/Blog/BlogDetails/@item.BlogID"><img src="@item.BlogImage" style="height:250px" alt="Image" class="img-fluid rounded"></a>
                        <div class="excerpt">
                            <span class="post-category text-white bg-secondary mb-3">@item.Category.CategoryName</span>

                            <h2><a href="/Blog/BlogDetails/@item.BlogID">@item.BlogTitle</a></h2>
                            <div class="post-meta align-items-center text-left clearfix">
                                <a href="/Author/AuthorAbout/@item.AuthorID"><figure class="author-figure mb-0 mr-3 float-left"><img src="@item.Author.AuthorImage" alt="Image" class="img-fluid"></figure></a>
                                <span class="d-inline-block mt-1"><a href="/Author/AuthorAbout/@item.AuthorID">@item.Author.AuthorName</a></span>
                                <span>&nbsp;-&nbsp; @(((DateTime)item.BlogDate).ToString("dd-MMM-yyyy"))</span>
                            </div>
                            <p>@item.BlogContent.Substring(0, item.BlogContent.Substring(0, 110).LastIndexOf(" "))...</p>
                            <p><a href="#">Devamını Oku</a></p>
                        </div>
                    </div>
                </div>
             }
        </div>
    </div>
</div>
@Html.Action("Footer", "About")

BlogProje/BlogProje/Views/Blog/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/Layoutt.cshtml";
}

<!--Burası öne çıkan postların partial'i-->
@Html.Action("FeaturedPosts", "Blog")

<!--Burası BlogListimin partial'i-->
@Html.Action("BlogList", "Blog")

<!--Burası MailSubsicript partial'i-->
@Html.Action("AddMail", "MailSubscribe")

<!--Burası Footer partial'i-->
@Html.Action("Footer","About")