BlogProje/BlogProje/Controllers/ChartController.cs
using BlogProje.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BlogProje.Controllers
{
    public class ChartController : Controller
    {
        // GET: Chart
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult VisualizeResult()
        {
            return Json(categorylist(), JsonRequestBehavior.AllowGet);
        }

        public List<Class1> categorylist()
        {
            List<Class1> c = new List<Class1>();

            c.Add(new Class1()
            {
                CategoryName="Tekoloji",
                BlogyCount=14
            });
            c.Add(new Class1()
            {
                CategoryName = "Spor",
                BlogyCount = 10
            });
            c.Add(new Class1()
            {
                CategoryName = "Sanat",
                BlogyCount = 8  
            });
            return c;
        }
    }
}

BlogProje/BlogProje/Views/Chart/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<!DOCTYPE html>

<html lang="en">

<head>

    <title>Grafikler</title>

    <script type="text/javascript" src="https://www.google.com/jsapi"></script>

    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>

    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>

    <script>

        $(document).ready(function () {

            $.ajax({

                type: "POST",

                dataType: "json",

                contentType: "application/json",

                url: '@Url.Action("VisualizeResult", "Chart")',

                success: function (result) {

                    google.charts.load('current', {

                        'packages': ['corechart']

                    });

                    google.charts.setOnLoadCallback(function () {

                        drawChart(result);

                    });

                }

            });

        });



        function drawChart(result) {

            var data = new google.visualization.DataTable();

            data.addColumn('string', 'Name');

            data.addColumn('number', 'Stoklar');

            var dataArray = [];



            $.each(result, function (i, obj) {

                dataArray.push([obj.CategoryName, obj.BlogCount]);

            });

            data.addRows(dataArray);



            var columnChartOptions = {

                title: "Kategori Blog Pie Grafik",

                width: 1000,

                height: 600,

                bar: { groupWidth: "20%" },

            };



            var columnChart = new google.visualization.PieChart(document

                .getElementById('Piechart_div'));



            columnChart.draw(data, columnChartOptions);

        }

    </script>

</head>

<body>

    <div id="Piechart_div"></div>

    <script src="~/AdminLTE-3.0.4/plugins/jquery/jquery.min.js"></script>
    <!-- Bootstrap 4 -->
    <script src="~/AdminLTE-3.0.4/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- AdminLTE App -->
    <script src="~/AdminLTE-3.0.4/dist/js/adminlte.min.js"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="~/AdminLTE-3.0.4/dist/js/demo.js"></script>

</body>

</html>